"""Create four general-publication figures for the RNALocate context-shortcut audit."""

from __future__ import annotations

import hashlib
import json
import platform
import shutil
from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results"
PAPER = ROOT
FIGURES = ROOT / "figures"
SOURCE = ROOT / "source_data"

BLUE = "#0072B2"
ORANGE = "#E69F00"
GREEN = "#009E73"
VERMILLION = "#D55E00"
PURPLE = "#CC79A7"
SKY = "#56B4E9"
BLACK = "#222222"
GRAY = "#7A7A7A"
LIGHT = "#E6E6E6"

MODEL_COLORS = {
    "prevalence": GRAY,
    "context_only": BLUE,
    "support_only": ORANGE,
    "sequence_only": GREEN,
    "context_sequence": SKY,
    "context_support": VERMILLION,
    "support_sequence": PURPLE,
    "full": BLACK,
}

MODEL_MARKERS = {
    "prevalence": "o",
    "context_only": "s",
    "support_only": "^",
    "sequence_only": "D",
    "context_sequence": "P",
    "context_support": "v",
    "support_sequence": "X",
    "full": "*",
}


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def panel_label(ax: mpl.axes.Axes, label: str) -> None:
    ax.text(-0.11, 1.06, label, transform=ax.transAxes, fontsize=11, fontweight="bold", va="top")


def style_axis(ax: mpl.axes.Axes) -> None:
    ax.spines[["top", "right"]].set_visible(False)
    ax.grid(axis="x", color=LIGHT, linewidth=0.6, zorder=0)
    ax.tick_params(labelsize=7.5)


def export_figure(fig: mpl.figure.Figure, stem: str, description: str, sources: list[str]) -> list[dict[str, object]]:
    FIGURES.mkdir(parents=True, exist_ok=True)
    records: list[dict[str, object]] = []
    for suffix in ("svg", "pdf", "png"):
        path = FIGURES / f"{stem}.{suffix}"
        metadata = {
            "Title": stem.replace("_", " ").title(),
            "Creator": "Matplotlib; generated by make_context_shortcut_figures.py",
            "Description": description,
        }
        if suffix == "pdf":
            metadata = {
                "Title": metadata["Title"],
                "Creator": metadata["Creator"],
                "Subject": description,
                "Keywords": "RNALocate, RNA localization, database coverage, context shortcut",
            }
        fig.savefig(
            path,
            dpi=300 if suffix == "png" else 600,
            facecolor="white",
            edgecolor="white",
            transparent=False,
            metadata=metadata,
        )
        if suffix == "png":
            with Image.open(path) as rendered:
                rgb = rendered.convert("RGB")
                rgb.save(path, format="PNG", dpi=(300, 300), optimize=True)
        record: dict[str, object] = {
            "file": str(path.relative_to(ROOT)).replace("\\", "/"),
            "format": suffix,
            "sha256": sha256(path),
            "bytes": path.stat().st_size,
            "source_tables": sources,
        }
        if suffix == "png":
            with Image.open(path) as image:
                record.update({"pixel_width": image.width, "pixel_height": image.height, "mode": image.mode, "dpi": image.info.get("dpi")})
        records.append(record)
    plt.close(fig)
    return records


def write_source(frame: pd.DataFrame, filename: str) -> str:
    SOURCE.mkdir(parents=True, exist_ok=True)
    path = SOURCE / filename
    frame.to_csv(path, sep="\t", index=False)
    return str(path.relative_to(ROOT)).replace("\\", "/")


def figure_1() -> tuple[list[dict[str, object]], list[str]]:
    per_context = pd.read_csv(RESULTS / "record_availability_by_context.tsv", sep="\t")
    context = per_context[per_context["model"].eq("context_support")].copy()
    pooled = pd.read_csv(RESULTS / "support_gradient.tsv", sep="\t")
    by_context = pd.read_csv(RESULTS / "support_gradient_by_context.tsv", sep="\t")
    source_paths = [
        write_source(context, "figure_1_context_coverage.tsv"),
        write_source(pooled, "figure_1_support_gradient.tsv"),
        write_source(by_context, "figure_1_support_by_context.tsv"),
    ]

    with mpl.rc_context({
        "font.family": "DejaVu Sans",
        "font.size": 8,
        "axes.titlesize": 9,
        "axes.labelsize": 8,
        "svg.fonttype": "none",
        "pdf.fonttype": 42,
    }):
        fig = plt.figure(figsize=(7.1, 7.0), layout="constrained")
        mosaic = fig.subplot_mosaic([["A", "B"], ["C", "C"]], height_ratios=[1.0, 1.12])
        ax_a, ax_b, ax_c = mosaic["A"], mosaic["B"], mosaic["C"]

        ordered = context.sort_values("prevalence")
        y = np.arange(len(ordered))
        ax_a.scatter(ordered["prevalence"], y, s=30, color=BLUE, marker="o", edgecolor="white", linewidth=0.5, zorder=3)
        ax_a.axvline(ordered["prevalence"].mean(), color=GRAY, linestyle="--", linewidth=1, label="Mean across contexts")
        ax_a.set_yticks(y, ordered["context"])
        ax_a.set_xlim(0, 1)
        ax_a.set_xlabel("Fraction of gene pairs with a record")
        ax_a.set_title("Record coverage varies by context")
        ax_a.legend(frameon=False, fontsize=7, loc="lower right")
        style_axis(ax_a)
        panel_label(ax_a, "A")

        support = pooled["other_context_support"].to_numpy()
        fraction = pooled["observed_fraction"].to_numpy()
        low = pooled["ci95_low"].to_numpy()
        high = pooled["ci95_high"].to_numpy()
        ax_b.fill_between(support, low, high, color=ORANGE, alpha=0.24, linewidth=0)
        ax_b.plot(support, fraction, color=ORANGE, marker="o", markersize=4, linewidth=1.4)
        ax_b.scatter([0], [fraction[0]], color=BLACK, marker="s", s=35, zorder=4, label="Selection boundary")
        ax_b.annotate(
            "Support = 0 is structurally observed\nin this selected gene panel",
            xy=(0, fraction[0]),
            xytext=(2.2, 0.84),
            arrowprops={"arrowstyle": "->", "color": BLACK, "linewidth": 0.8},
            fontsize=7,
        )
        ax_b.set(xlim=(-0.4, 15.4), ylim=(0, 1.03), xlabel="Records for the same gene in other contexts", ylabel="Current-context record fraction")
        ax_b.set_title("Cross-context coverage gradient")
        ax_b.set_xticks(range(0, 16, 2))
        ax_b.legend(frameon=False, fontsize=7, loc="lower right")
        style_axis(ax_b)
        panel_label(ax_b, "B")

        context_order = ordered["context"].tolist()
        pivot = by_context.pivot(index="context", columns="other_context_support", values="observed_fraction").reindex(context_order)
        cmap = mpl.colormaps["viridis"].copy()
        cmap.set_bad("#D9D9D9")
        image = ax_c.imshow(pivot.to_numpy(), aspect="auto", vmin=0, vmax=1, cmap=cmap, interpolation="nearest")
        ax_c.set_yticks(np.arange(len(context_order)), context_order)
        ax_c.set_xticks(np.arange(16), [str(i) for i in range(16)])
        ax_c.set_xlabel("Other-context support")
        ax_c.set_title("Coverage association differs across contexts")
        colorbar = fig.colorbar(image, ax=ax_c, fraction=0.024, pad=0.02)
        colorbar.set_label("Observed fraction", fontsize=8)
        colorbar.ax.tick_params(labelsize=7)
        ax_c.tick_params(labelsize=7)
        panel_label(ax_c, "C")

        records = export_figure(
            fig,
            "figure_1_database_coverage",
            "Context-specific RNALocate record coverage and its association with same-gene records in other contexts.",
            source_paths,
        )
    return records, source_paths


def figure_2() -> tuple[list[dict[str, object]], list[str]]:
    metrics = pd.read_csv(RESULTS / "record_availability_metrics.tsv", sep="\t")
    effects = pd.read_csv(RESULTS / "record_availability_incremental_effects.tsv", sep="\t")
    permutation = pd.read_csv(RESULTS / "shuffled_support_control.tsv", sep="\t")
    source_paths = [
        write_source(metrics, "figure_2_factorial_metrics.tsv"),
        write_source(effects, "figure_2_incremental_effects.tsv"),
        write_source(permutation, "figure_2_shuffled_support.tsv"),
    ]

    with mpl.rc_context({"font.family": "DejaVu Sans", "font.size": 8, "axes.titlesize": 9, "axes.labelsize": 8, "svg.fonttype": "none", "pdf.fonttype": 42}):
        fig = plt.figure(figsize=(7.1, 7.2), layout="constrained")
        mosaic = fig.subplot_mosaic([["A", "A"], ["B", "C"]], height_ratios=[1.25, 1.0])
        ax_a, ax_b, ax_c = mosaic["A"], mosaic["B"], mosaic["C"]

        order = list(metrics.sort_values("average_precision")["model"])
        view = metrics.set_index("model").loc[order].reset_index()
        y = np.arange(len(view))
        for row_index, row in view.iterrows():
            model = row["model"]
            ax_a.errorbar(
                row["average_precision"], row_index,
                xerr=[[row["average_precision"] - row["ap_ci95_low"]], [row["ap_ci95_high"] - row["average_precision"]]],
                fmt=MODEL_MARKERS[model], color=MODEL_COLORS[model], markersize=6 if model != "full" else 8,
                capsize=2, linewidth=1.2, markeredgecolor="white", markeredgewidth=0.4,
            )
            ax_a.text(row["average_precision"] + 0.004, row_index, f"{row['average_precision']:.3f}", va="center", fontsize=7)
        ax_a.set_yticks(y, view["display_name"])
        ax_a.set_xlim(0.65, 0.98)
        ax_a.set_xlabel("Average precision (95% component-bootstrap CI)")
        ax_a.set_title("Complete context × support × sequence model matrix")
        style_axis(ax_a)
        panel_label(ax_a, "A")

        labels = {
            "sequence_after_context": "Sequence after context",
            "support_after_context": "Support after context",
            "sequence_after_context_support": "Sequence after context + support",
            "support_after_context_sequence": "Support after context + sequence",
        }
        effect_view = effects.copy()
        effect_view["label"] = effect_view["contrast"].map(labels)
        effect_view = effect_view.sort_values("ap_difference")
        yb = np.arange(len(effect_view))
        ax_b.axvline(0, color=GRAY, linewidth=0.8)
        ax_b.errorbar(
            effect_view["ap_difference"], yb,
            xerr=[effect_view["ap_difference"] - effect_view["ap_difference_ci95_low"], effect_view["ap_difference_ci95_high"] - effect_view["ap_difference"]],
            fmt="o", color=BLUE, markersize=5, capsize=2, linewidth=1.2,
        )
        ax_b.set_yticks(yb, effect_view["label"])
        ax_b.set_xlabel("Paired AP difference")
        ax_b.set_title("Incremental information")
        style_axis(ax_b)
        panel_label(ax_b, "B")

        rng = np.random.default_rng(20260814)
        jitter = rng.normal(0, 0.035, len(permutation))
        ax_c.scatter(permutation["average_precision"], jitter, s=11, color=SKY, alpha=0.55, marker="o", label="Shuffled support (n=200)")
        real = float(permutation["real_context_support_ap"].iloc[0])
        ax_c.scatter([real], [0], s=85, color=VERMILLION, marker="D", edgecolor="white", linewidth=0.7, label="Real same-gene support")
        ax_c.axvline(float(permutation["average_precision"].median()), color=BLUE, linestyle="--", linewidth=1)
        ax_c.set(xlim=(0.795, 0.965), ylim=(-0.16, 0.16), xlabel="Average precision", yticks=[])
        ax_c.set_title("Same-gene linkage negative control")
        ax_c.legend(frameon=False, fontsize=7, loc="upper center")
        style_axis(ax_c)
        panel_label(ax_c, "C")

        records = export_figure(
            fig,
            "figure_2_factorial_and_permutation",
            "Eight record-availability models, paired incremental effects, and 200 within-context shuffled-support refits.",
            source_paths,
        )
    return records, source_paths


def figure_3() -> tuple[list[dict[str, object]], list[str]]:
    context = pd.read_csv(RESULTS / "record_availability_by_context.tsv", sep="\t")
    calibration = pd.read_csv(RESULTS / "calibration_bins.tsv", sep="\t")
    sensitivity = pd.read_csv(RESULTS / "sequence_view_sensitivity.tsv", sep="\t")
    source_paths = [
        write_source(context, "figure_3_context_metrics.tsv"),
        write_source(calibration, "figure_3_calibration.tsv"),
        write_source(sensitivity, "figure_3_sequence_sensitivity.tsv"),
    ]

    cs = context[context["model"].eq("context_support")].set_index("context")
    full = context[context["model"].eq("full")].set_index("context")
    ordered_contexts = cs.sort_values("average_precision").index.tolist()
    with mpl.rc_context({"font.family": "DejaVu Sans", "font.size": 8, "axes.titlesize": 9, "axes.labelsize": 8, "svg.fonttype": "none", "pdf.fonttype": 42}):
        fig = plt.figure(figsize=(7.1, 7.3), layout="constrained")
        mosaic = fig.subplot_mosaic([["A", "B"], ["C", "D"]])
        ax_a, ax_b, ax_c, ax_d = (mosaic[key] for key in "ABCD")

        y = np.arange(len(ordered_contexts))
        prevalence = cs.loc[ordered_contexts, "prevalence"].to_numpy()
        ap = cs.loc[ordered_contexts, "average_precision"].to_numpy()
        for yi, left, right in zip(y, prevalence, ap):
            ax_a.plot([left, right], [yi, yi], color=LIGHT, linewidth=2, zorder=1)
        ax_a.scatter(prevalence, y, color=GRAY, marker="o", s=23, label="Prevalence", zorder=2)
        ax_a.scatter(ap, y, color=VERMILLION, marker="D", s=25, label="Context + support AP", zorder=3)
        ax_a.set_yticks(y, ordered_contexts)
        ax_a.set_xlim(0.3, 1.01)
        ax_a.set_xlabel("Fraction / average precision")
        ax_a.set_title("Performance across 16 contexts")
        ax_a.legend(frameon=False, fontsize=7, loc="lower right")
        style_axis(ax_a)
        panel_label(ax_a, "A")

        increment = full.loc[ordered_contexts, "average_precision"] - cs.loc[ordered_contexts, "average_precision"]
        colors = np.where(increment >= 0, GREEN, VERMILLION)
        ax_b.axvline(0, color=GRAY, linewidth=0.8)
        ax_b.barh(y, increment, color=colors, alpha=0.85)
        ax_b.set_yticks(y, ordered_contexts)
        ax_b.set_xlabel("Full minus context + support AP")
        ax_b.set_title("Sequence increment by context")
        style_axis(ax_b)
        panel_label(ax_b, "B")

        ax_c.plot([0, 1], [0, 1], color=GRAY, linestyle="--", linewidth=1, label="Perfect calibration")
        for model, marker in (("context_only", "s"), ("context_support", "v"), ("full", "*")):
            frame = calibration[calibration["model"].eq(model)]
            ax_c.errorbar(
                frame["mean_predicted_probability"], frame["observed_fraction"],
                yerr=[frame["observed_fraction"] - frame["ci95_low"], frame["ci95_high"] - frame["observed_fraction"]],
                marker=marker, color=MODEL_COLORS[model], linewidth=1.1, markersize=5,
                capsize=1.5, label=frame["display_name"].iloc[0],
            )
        ax_c.set(xlim=(0, 1), ylim=(0, 1), xlabel="Mean predicted probability", ylabel="Observed fraction")
        ax_c.set_title("Reliability diagram")
        ax_c.legend(frameon=False, fontsize=6.7, loc="upper left")
        style_axis(ax_c)
        panel_label(ax_c, "C")

        view_labels = {"composition_length": "Composition + length", "three_mer_only": "3-mer only", "complete_70": "Complete 70"}
        modes = [("sequence_only", GREEN, "o", "Sequence only"), ("full", BLACK, "D", "Context + support + sequence")]
        x = np.arange(3)
        for model, color, marker, label in modes:
            frame = sensitivity[sensitivity["model"].eq(model)].set_index("feature_view").loc[list(view_labels)]
            ax_d.plot(x, frame["average_precision"], marker=marker, color=color, linewidth=1.2, markersize=5, label=label)
        ax_d.set_xticks(x, [view_labels[key] for key in view_labels], rotation=18, ha="right")
        ax_d.set_ylim(0.76, 0.97)
        ax_d.set_ylabel("Average precision")
        ax_d.set_title("Low-level sequence-view sensitivity")
        ax_d.legend(frameon=False, fontsize=6.7, loc="lower right")
        style_axis(ax_d)
        panel_label(ax_d, "D")

        records = export_figure(
            fig,
            "figure_3_robustness_and_calibration",
            "Context heterogeneity, sequence increments, probability calibration, and sensitivity to low-level sequence feature views.",
            source_paths,
        )
    return records, source_paths


def figure_4() -> tuple[list[dict[str, object]], list[str]]:
    global_metrics = pd.read_csv(SOURCE / "figure_4_global_annotation_recovery.tsv", sep="\t")
    global_models = ["label_frequency", "sequence_3mer", "context_only", "sequence_3mer_plus_context"]
    global_view = global_metrics[global_metrics["model"].isin(global_models)].copy()
    per_label = pd.read_csv(SOURCE / "figure_4_per_label_annotation_recovery.tsv", sep="\t")
    per_label_view = per_label[per_label["model"].isin(global_models)].copy()
    within = pd.read_csv(SOURCE / "figure_4_within_context.tsv", sep="\t")
    within_models = ["context_only", "sequence_3mer", "sequence_3mer_plus_context"]
    within_view = within[within["model"].isin(within_models)].copy()
    split = pd.read_csv(SOURCE / "figure_4_split_sensitivity.tsv", sep="\t")
    source_paths = [
        write_source(global_view, "figure_4_global_annotation_recovery.tsv"),
        write_source(per_label_view, "figure_4_per_label_annotation_recovery.tsv"),
        write_source(within_view, "figure_4_within_context.tsv"),
        write_source(split, "figure_4_split_sensitivity.tsv"),
    ]

    names = {
        "label_frequency": "Prevalence",
        "sequence_3mer": "Low-level sequence",
        "context_only": "Context",
        "sequence_3mer_plus_context": "Context + sequence",
    }
    colors = {
        "label_frequency": GRAY,
        "sequence_3mer": GREEN,
        "context_only": BLUE,
        "sequence_3mer_plus_context": SKY,
    }
    markers = {"label_frequency": "o", "sequence_3mer": "D", "context_only": "s", "sequence_3mer_plus_context": "P"}
    with mpl.rc_context({"font.family": "DejaVu Sans", "font.size": 8, "axes.titlesize": 9, "axes.labelsize": 8, "svg.fonttype": "none", "pdf.fonttype": 42}):
        fig = plt.figure(figsize=(7.1, 7.25), layout="constrained")
        mosaic = fig.subplot_mosaic([["A", "B"], ["C", "D"]])
        ax_a, ax_b, ax_c, ax_d = (mosaic[key] for key in "ABCD")

        view = global_view.set_index("model").loc[global_models].reset_index()
        y = np.arange(len(view))
        for idx, row in view.iterrows():
            model = row["model"]
            ax_a.errorbar(
                row["macro_ap"], idx,
                xerr=[[row["macro_ap"] - row["ci95_low"]], [row["ci95_high"] - row["macro_ap"]]],
                fmt=markers[model], color=colors[model], markersize=6, capsize=2, linewidth=1.2,
            )
        ax_a.set_yticks(y, [names[x] for x in view["model"]])
        ax_a.set_xlim(0.25, 0.80)
        ax_a.set_xlabel("Macro average precision (95% CI)")
        ax_a.set_title("Recovery of recorded localization labels")
        style_axis(ax_a)
        panel_label(ax_a, "A")

        label_order = ["nucleus", "cytoplasm", "endoplasmic_reticulum", "mitochondrion"]
        label_names = ["Nucleus", "Cytoplasm", "ER", "Mitochondrion"]
        offsets = np.linspace(-0.24, 0.24, len(global_models))
        x = np.arange(len(label_order))
        for offset, model in zip(offsets, global_models):
            frame = per_label_view[per_label_view["model"].eq(model)].set_index("label").loc[label_order]
            ax_b.scatter(x + offset, frame["average_precision"], color=colors[model], marker=markers[model], s=28, label=names[model])
        ax_b.set_xticks(x, label_names, rotation=18, ha="right")
        ax_b.set_ylim(0, 1.03)
        ax_b.set_ylabel("Average precision")
        ax_b.set_title("The aggregate result is label-dependent")
        ax_b.legend(frameon=False, fontsize=6.2, loc="center left")
        style_axis(ax_b)
        panel_label(ax_b, "B")

        w = within_view.set_index("model").loc[within_models].reset_index()
        yc = np.arange(len(w))
        for idx, row in w.iterrows():
            model = row["model"]
            ax_c.errorbar(
                row["mean_within_context_ap"], idx,
                xerr=[[row["mean_within_context_ap"] - row["ci95_low"]], [row["ci95_high"] - row["mean_within_context_ap"]]],
                fmt=markers[model], color=colors[model], markersize=6, capsize=2, linewidth=1.2,
            )
        ax_c.set_yticks(yc, [names[x] for x in w["model"]])
        ax_c.set_xlim(0.40, 0.57)
        ax_c.set_xlabel("Mean within-context AP (95% CI)")
        ax_c.set_title("Sequence retains within-context information")
        style_axis(ax_c)
        panel_label(ax_c, "C")

        partition_labels = ["80/80 graph", "70/80 cluster", "60/80 cluster", "80/50 cluster"]
        xd = np.arange(len(split))
        ax_d.plot(xd, split["internal_context_macro_ap"], marker="s", color=BLUE, linewidth=1.2, label="Context")
        ax_d.plot(xd, split["internal_3mer_macro_ap"], marker="D", color=GREEN, linewidth=1.2, label="Low-level sequence")
        ax_d.set_xticks(xd, partition_labels, rotation=22, ha="right")
        ax_d.set_ylim(0.25, 0.76)
        ax_d.set_ylabel("Macro average precision")
        ax_d.set_title("Result is stable across tested partitions")
        ax_d.legend(frameon=False, fontsize=7, loc="center right")
        style_axis(ax_d)
        panel_label(ax_d, "D")

        records = export_figure(
            fig,
            "figure_4_annotation_recovery_consequence",
            "Global, per-label, within-context, and split-sensitivity results for recovery of recorded RNALocate localization labels.",
            source_paths,
        )
    return records, source_paths


def write_captions() -> None:
    text = """# Figure captions and accessible descriptions

These are provisional general-publication figures. No target-journal or submission-phase compliance is claimed.

## Figure 1 | RNALocate database coverage is structured by context and same-gene cross-context support

**Caption.** (A) Fraction of candidate gene pairs with at least one retained RNALocate record in each of 16 contexts. The dashed line is the unweighted mean across contexts. (B) Test-set record fraction by the number of records for the same gene in the other 15 contexts. Shading shows Wilson 95% confidence intervals for binomial proportions. Support zero is marked as a cohort-selection boundary: every eligible gene has at least one retained record, so a gene with zero records in all other contexts must have a record in the candidate context. (C) Context-specific record fractions across support values; gray cells are combinations absent from the test set. These panels describe database coverage co-occurrence, not biological localization or a causal dose response.

**Alt text.** Three panels show substantial variation in RNALocate record coverage. Context fractions range from roughly one third to nearly all candidate genes. Except for the structurally constrained support-zero point, record availability generally rises as the same gene is recorded in more other contexts, with visible differences among contexts.

## Figure 2 | Context and same-gene support explain most predictable record availability

**Caption.** (A) Held-out average precision for the prevalence baseline and all seven non-empty combinations of context, target-excluding other-context support, and low-level sequence features. Error bars are 95% intervals from 1,000 bootstrap resamples of all-sequence graph components. The displayed nonzero axis is used for point estimates and intervals, not lengths. (B) Paired AP increments from the same bootstrap replicates. (C) Average precision from 200 controls in which support was shuffled among genes separately within every context and split, compared with the real same-gene context-plus-support model. Shuffling preserves context-specific support distributions but breaks the gene-support linkage. It does not identify measurement, publication, or curation mechanisms.

**Alt text.** The complete model has AP about 0.958. Context plus support is nearly identical, whereas context plus sequence is about 0.882. Adding sequence after context plus support changes AP by less than 0.001. All 200 shuffled-support models cluster near 0.811, far below the real context-plus-support result near 0.957.

## Figure 3 | Coverage prediction is heterogeneous but robust to tested low-level sequence views

**Caption.** (A) Prevalence and context-plus-support AP for each context. Connecting segments visualize AP lift without treating it as a causal effect. (B) Per-context AP difference after adding the complete low-level sequence vector to context plus support; green and vermillion encode positive and negative values with direction also represented by position relative to zero. (C) Equal-frequency reliability bins for context, context plus support, and the full model; vertical intervals are Wilson 95% confidence intervals for observed fractions. (D) Sensitivity to composition-plus-length, normalized 3-mer-only, and complete 70-feature sequence views in sequence-only and full models. The tested low-level views do not represent all possible RNA sequence models.

**Alt text.** Context-plus-support AP exceeds prevalence in every context, although performance is much weaker in IMR-90 than elsewhere. Adding sequence produces small and context-dependent changes. Context plus support and the full model track the calibration diagonal more closely than context alone. Stronger low-level sequence views improve sequence-only AP but barely alter the full model.

## Figure 4 | Database structure has a clear consequence for localization annotation recovery

**Caption.** (A) Macro average precision for recovering four recorded localization labels among already observed gene-context rows. Error bars are existing 95% graph-component bootstrap intervals. (B) Per-label average precision; the high nucleus prevalence and very low endoplasmic-reticulum prevalence make endpoint-specific results essential. (C) Mean average precision across the five eligible non-nucleus context-label cells with at least ten positive and ten negative test rows. A context-only model is constant within a context, whereas low-level sequence can rank genes. (D) Context and low-level-sequence macro AP under the primary exhaustive sequence graph and three MMseqs2 clustering stress tests. These analyses concern database annotations and do not validate localization for unrecorded pairs.

**Alt text.** Context strongly outperforms low-level sequence in aggregate annotation recovery, while combining both is best among the four simple models. Results differ sharply by localization label. Within fixed contexts, sequence improves mean AP over the constant context baseline. Context dominance is stable across four tested sequence-component partitions.
"""
    (PAPER / "figure_captions.md").write_text(text, encoding="utf-8")


def main() -> None:
    FIGURES.mkdir(parents=True, exist_ok=True)
    SOURCE.mkdir(parents=True, exist_ok=True)
    records: list[dict[str, object]] = []
    source_groups: dict[str, list[str]] = {}
    for index, builder in enumerate((figure_1, figure_2, figure_3, figure_4), start=1):
        figure_records, sources = builder()
        records.extend(figure_records)
        source_groups[f"figure_{index}"] = sources
        print(f"created figure {index}", flush=True)
    write_captions()

    manifest = {
        "status": "general publication figures; target-journal compliance pending",
        "generated_by": "scripts/make_figures.py",
        "software": {
            "python": platform.python_version(),
            "matplotlib": mpl.__version__,
            "pandas": pd.__version__,
            "numpy": np.__version__,
        },
        "background": "opaque white",
        "raster_dpi_requested": 300,
        "svg_text": "editable/searchable text; fonts are not embedded",
        "source_groups": source_groups,
        "files": records,
    }
    (FIGURES / "figure_manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    shutil.copy2(ROOT / "analysis_plan.md", SOURCE / "analysis_plan_snapshot.md")
    print(json.dumps({"figure_files": len(records), "source_tables": sum(map(len, source_groups.values()))}, indent=2))


if __name__ == "__main__":
    main()
